[workspace]

members = [
    "snapfaas",
    #"frontends/httpserver",
    # TODO webhook needs migrating to use scheduler rpc "frontends/webhook",
    "frontends/webfront",
]

[profile.dev]
opt-level = 1

[patch.crates-io]
raft-proto = { git = "https://github.com/tikv/raft-rs", rev="95c532612ee6a83591fce9a8b51d6afe87b58835"}
protobuf = { git = "https://github.com/pingcap/rust-protobuf", rev="82b49fea7e696fd647b5aca0a6c6ec944eab3189" }
